# Generated by Django 5.0.7 on 2024-07-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='no_of_com',
            field=models.IntegerField(null=True),
        ),
    ]
