# Generated by Django 5.0.7 on 2024-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_author_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
