# Generated by Django 5.0.7 on 2024-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comment_user_alter_blogpost_author_userpicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='profile_pic',
            field=models.ImageField(default='default-pic.jpg', upload_to='profile_pics'),
        ),
    ]
