# Generated by Django 5.0.7 on 2024-08-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_userpicture_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='posts_pics'),
        ),
    ]
